{% set name = "google-cloud-orchestration-airflow" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-orchestration-airflow-{{ version }}.tar.gz
  sha256: f417c2c298694a13233488d8e0004a26daddb6cc0229ddbb82232c9fbc5508d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core >=1.34.1,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-orchestration-airflow
  summary: Google Cloud Orchestration Airflow API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
